*********************************************************************************************************** 
* WARNING: This modules-environment is intended for users whose applications
and locally compiled codes * 
* depend on toolchains previously available on Cartesius in the 2020 software
stack. Please * 
* note that this modules-environment does not and WILL NOT include a complete
software stack. * 
* * 
* If you have any question, please contact us via
http://servicedesk.surfsara.nl. * 
*********************************************************************************************************** 
Device used: cuda:0
Loading data...
Traceback (most recent call last):
  File "/home/dmarz/anaconda3/envs/deeprank/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'measurement_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home6/dmarz/3D-Vac/src/5_train_models/CNN/II/classification/seq/mlp_baseline.py", line 175, in <module>
    csv_peptides, csv_labels, groups = load_class_seq_data(csv_path, a.threshold)
  File "/gpfs/home6/dmarz/3D-Vac/src/5_train_models/CNN/datasets.py", line 145, in load_class_seq_data
    labels = [(0.,1.,)[value < threshold] for value in df["measurement_value"]]
  File "/home/dmarz/anaconda3/envs/deeprank/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/dmarz/anaconda3/envs/deeprank/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'measurement_value'
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 1271272 ON gcn16 CANCELLED AT 2022-07-28T05:37:18 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 1271272.0 ON gcn16 CANCELLED AT 2022-07-28T05:37:18 DUE TO TIME LIMIT ***

JOB STATISTICS
==============
Job ID: 1271272
Cluster: snellius
User/Group: dmarz/dmarz
State: TIMEOUT (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 3-18:03:09
CPU Efficiency: 50.02% of 7-12:03:00 core-walltime
Job Wall-clock time: 10:00:10
Memory Utilized: 2.84 GB (estimated maximum)
Memory Efficiency: 0.00% of 0.00 MB (0.00 MB/node)
